### ISSUE TITLE
images not showing when Thank-you-like plugin is active 

### ISSUE THREAD

**Issue by arslanu** [Cu8eR/MyBB_Thank-you-like-plugin#102]
If TYL plugin is deactived then images attached is normal and showing. But if plugin is activated images not showing.

**Comment by Cu8eR** [comment]
@arslanu - without any screnshots, url and how to reproduce I cannot help you.

**Comment by arslanu** [comment]
![activated](https://cloud.githubusercontent.com/assets/16904471/12591241/83c9bc12-c46f-11e5-91eb-a6555385330d.jpg)
![deactiveted](https://cloud.githubusercontent.com/assets/16904471/12591242/83cb25e8-c46f-11e5-8db2-8d26fd826054.jpg)
![plugin](https://cloud.githubusercontent.com/assets/16904471/12591243/83cf4b00-c46f-11e5-8f27-ff4cd1e47345.jpg)

Which page do you want to see? I will send its screenshoot.

**Comment by Cu8eR** [comment]
It is a conflict in your forum. Try to disable all plugins and uninstall TYL plugin. Then install TYL plugin and activate.... try and write me. 

If it wont help, post me content from postbit template

**Comment by arslanu** [comment]
I did you wrote above. But still images are not showing. Here are postbit template:

{$ignore_bit}
<a name="pid{$post['pid']}" id="pid{$post['pid']}"></a>
<div class="post {$unapproved_shade}" style="{$post_visibility}" id="post_{$post['pid']}">
<div class="post_author">
	{$post['useravatar']}
	<div class="author_information">
			<strong><span class="largetext">{$post['profilelink']}</span></strong> {$post['onlinestatus']}<br />
			<span class="smalltext">
				{$post['usertitle']}<br />
				{$post['userstars']}
				{$post['groupimage']}
			</span>
	</div>
	<div class="author_statistics">
		{$post['user_details']}
	</div>
</div>
<div class="post_content">
	<div class="post_head">
		{$post['posturl']}
		{$post['icon']}
		<span class="post_date">{$post['postdate']} <span class="post_edit" id="edited_by_{$post['pid']}">{$post['editedmsg']}</span></span>
		{$post['subject_extra']}
	</div>
	<div class="post_body scaleimages" id="pid_{$post['pid']}">
		{$post['message']}
	</div>
	{$post['attachments']}
	{$post['signature']}
	<div class="post_meta" id="post_meta_{$post['pid']}">
		{$post['iplogged']}
	</div>
</div>
<div style="{$post['tyl_display']}" id="tyl_{$post['pid']}">{$post['thankyoulike_data']}</div>
<div class="post_controls">
	<div class="postbit_buttons author_buttons float_left">
		{$post['button_email']}{$post['button_pm']}{$post['button_www']}{$post['button_find']}{$post['button_rep']}
	</div>
	<div class="postbit_buttons post_management_buttons float_right">
		{$post['button_tyl']}{$post['button_edit']}{$post['button_quickdelete']}{$post['button_quickrestore']}{$post['button_quote']}{$post['button_multiquote']}{$post['button_report']}{$post['button_warn']}{$post['button_purgespammer']}{$post['button_reply_pm']}{$post['button_replyall_pm']}{$post['button_forward_pm']}{$post['button_delete_pm']}
	</div>
</div>
</div>

**Comment by Cu8eR** [comment]
With this info I cannot help. Do you use a custom theme? also check showthread and headerinclude templates for duplicates

**Comment by arslanu** [comment]
I use default theme. Will I check to duplicate what? I don't understand, please write details and I can chack it

**Comment by Cu8eR** [comment]
I am sorry, I have been quite busy lately. Check template additions according to the first post in TYL plugin in Mybb.com forum.
